### PR TITLE
Finish Awareness refactoring (to use Dictionary)

### LINKED ISSUE #224: Refactor Awareness to be composed of a Dictionary
I realised there can be better separation of concerns within the Awarenes class.
The class will be composed of 2 objects:

- Dictionary: Responsible to manage mappings between slang and full phrases
Operations supported:
  - Register a new slang - full phrase mapping: Throws IllegalValueException if the slang is invalid
  - Register a full phrase without any associated slang. Throws IllegalValueException if full phrase is invalid. 
  - Retrieve the possibleEventName associated with a given expression.

Awareness will act as a "facade" over the Dictionary

- TreeMap: Responsible to manage mappings between eventNames and ResumeEntries

### PR DESCRIPTION
**Pull request by anubh-v**
Fully fixes #224 

- SampleDataUtil now creates a sample dictionary (meant for Awareness object)
- I've also added a utility method to Dictionary that allows register multiple slang to a single full phrase
- The Dictionary related tests have been migrated from AwarenessTest to DictionaryTest
- **There is a deprecated constructor in the Awareness.java.** This is required because the XmlSerializableAwareness code uses the old constructor. It will be removed very soon (once this PR is merged)

### CODE REVIEW

File: src/test/java/seedu/address/model/AwarenessTest.java [hunk 1]
```diff
@@ -18,76 +22,40 @@
     @Test
     public void constructor_null_throwsNullPointerException() {
         thrown.expect(NullPointerException.class);
-        new Awareness(null, null);
-    }
-
-    @Test
-    public void getPossibleEventName_postiveMatches() {
```
Comment (ongspxm) [inline src/test/java/seedu/address/model/AwarenessTest.java]: Can keep as integration test within dictinary and awareness.

Comment (ongspxm) [reply src/test/java/seedu/address/model/AwarenessTest.java]: Eh... but i guess since its added to dict already, its fine
